version: "3"

services:
  api:
    container_name: full-stack-api
    build:
      context: ./api
      dockerfile: dockerfile
    env_file:
      - ./ops/localhost.env
    ports:
      - "3001:3001"
    networks:
      - full-stack-net
    volumes:
      - ./api:/full-stack/api
  db:
    container_name: full-stack-db
    build:
      context: ./db
      dockerfile: dockerfile
    env_file:
      - ./ops/localhost.env
    ports:
      - "3306:3306"
    networks:
      - full-stack-net
    volumes:
      - dbdata:/var/lib/mysql1
  web:
    container_name: full-stack-web
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - full-stack-net
    volumes:
      - ./ops:/full-stack/ops
      - ./web:/full-stack/web
    env_file:
      - ./ops/localhost.env

networks:
  full-stack-net:
    driver: bridge

volumes:
  dbdata: