version: "3"

services:
  db:
    container_name: full-stack-db
    build:
      context: ./db
      dockerfile: dockerfile
    env_file:
      - ./ops/localhost.env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql1

volumes:
  dbdata:

networks:
  full-stack-net:
    driver: bridge