FROM        node:10

ENV         NPM_CONFIG_LOGLEVEL warn

RUN         npm install -g nodemon

RUN         mkdir -p /full-stack/api

WORKDIR     /full-stack/api

EXPOSE      3001

RUN mkdir -p /full-stack/api/node_modules && chown -R node:node /full-stack/api

ENTRYPOINT  ["sleep", "2d"]
